#autogenerated template for test generation
#just implement the function and update it in main

import os
import sys
import random as rnd 



def test00():
	pass


def test01():
	pass



def test02():
	pass


def test03():
	pass

def test04():
	pass

def test05():
	pass

def test06():
	pass


def test07():
	pass


def test08():
	pass


def test09():
	pass


def test10():
	pass


def main():
	tests = [test00, test01,test02,test03,test04,test05,test06,test07,test08,test09,test10]
	i = int(sys.argv[1])
	tests[i]()


def test_func():
	tests = [test00, test01,test02,test03,test04,test05,test06,test07,test08,test09,test10]

	for i in range(10):
		test[i]()



